// src/app/data/cars.js
const cars = [
  {
    image: "/images/cars/car-1.svg",
    name: "Koenigsegg",
    price: 99,
    discount: " ",
    category: "Sport",
    genre: "Manual",
    litres: 90,
    people: 2,
  },
  {
    image: "/images/cars/car-2.svg",
    name: "Nissan GT - R",
    price: 80,
    discount: "$100",
    category: "Sport",
    genre: "Manual",
    litres: 80,
    people: 2,
  },
  {
    image: "/images/cars/car-3.svg",
    name: "Rolls - Royce",
    price: 96,
    discount: " ",
    category: "Sedan",
    genre: "Manual",
    litres: 70,
    people: 4,
  },
  {
    image: "/images/cars/car-4.svg",
    name: "Nissan GT - R",
    price: 80,
    discount: "$100",
    category: "Sport",
    genre: "Manual",
    litres: 80,
    people: 2,
  },

  {
    image: "/images/cars/car-5.svg",
    name: "All New Rush",
    price: 72,
    discount: "$80.00",
    category: "SUV",
    genre: "Manual",
    litres: 70,
    people: 6,
  },
  {
    image: "/images/cars/car-6.svg",
    name: "CR - V",
    price: 80,
    discount: " ",
    category: "SUV",
    genre: "Manual",
    litres: 80,
    people: 6,
  },
  {
    image: "/images/cars/car-7.svg",
    name: "All New Terios",
    price: 74,
    discount: " ",
    category: "SUV",
    genre: "Manual",
    litres: 90,
    people: 6,
  },
  {
    image: "/images/cars/car-6.svg",
    name: "CR  - V",
    price: 80,
    discount: " ",
    category: "SUV",
    genre: "Manual",
    litres: 80,
    people: 6,
  },
  {
    image: "/images/cars/car-9.svg",
    name: "MG ZX Exclusice",
    price: 76,
    discount: "$80.00",
    category: "Hatchback",
    genre: "Manual",
    litres: 70,
    people: 4,
  },
  {
    image: "/images/cars/car-10.svg",
    name: "New MG ZS",
    price: 80,
    category: "SUV",
    genre: "Manual",
    litres: 80,
    people: 6,
  },
  {
    image: "/images/cars/car-11.svg",
    name: "MG ZX Excite",
    price: 74,
    discount: " ",
    category: "Hatchback",
    genre: "Manual",
    litres: 90,
    people: 4,
  },
  {
    image: "/images/cars/car-10.svg",
    name: "New MG ZS",
    price: 80,
    category: "SUV",
    genre: "Manual",
    litres: 80,
    people: 6,
  },
];

export default cars;
